// Generated by CoffeeScript 1.6.3
var Q, fs, log, path, pathExists, readDir, readFile, util, writeFile, _;

fs = require('fs');

path = require('path');

_ = require('underscore');

Q = require('q');

util = require(path.resolve(__dirname, './', 'util'));

log = require(path.resolve(__dirname, './', 'log'));

readDir = Q.denodeify(fs.readdir);

readFile = Q.denodeify(fs.readFile);

writeFile = Q.denodeify(fs.writeFile);

pathExists = Q.denodeify(fs.exists);

module.exports = function(args) {
  var inDir, outDir, results;
  console.time('time-to-run');
  inDir = path.resolve(__dirname, '..', 'test', 'inDir');
  outDir = path.resolve(__dirname, '..', 'test', 'outDir');
  results = [];
  return pathExists(inDir, function(exists) {
    if (exists) {
      return readDir(inDir).then(function(files) {
        return util.filterNonSvgFiles(files);
      }).then(function() {
        var resultsTemp;
        resultsTemp = require(path.resolve(__dirname, '../test', 'results.json'));
        return util.createCssRules(resultsTemp);
      }).then(function(cssString) {
        return console.log(util.prettyCss(cssString));
      }).then(function() {}).fail(function(error) {
        return log.data('error', error);
      })["finally"](function() {
        return console.timeEnd('time-to-run');
      }).done();
    } else {
      return log.msg('error', 'wrongDirectory');
    }
  });
};
