// Generated by CoffeeScript 1.6.3
var Q, colors, fs, microtime, msg, path, pathExists, readDir, readFile, util, writeFile, _;

fs = require('fs');

path = require('path');

_ = require('underscore');

Q = require('q');

colors = require('colors');

microtime = require('microtime');

util = require(path.resolve(__dirname, './', 'util'));

msg = require(path.resolve(__dirname, './', 'msg'));

readDir = Q.denodeify(fs.readdir);

readFile = Q.denodeify(fs.readFile);

writeFile = Q.denodeify(fs.writeFile);

pathExists = Q.denodeify(fs.exists);

module.exports = function(args, opts) {
  var cssFilename, iconrHeader, inDir, log, outDir, results, resultsTemp;
  inDir = path.resolve(__dirname, '..', 'test', 'inDir');
  outDir = path.resolve(__dirname, '..', 'test', 'outDir');
  resultsTemp = require(path.resolve(__dirname, '../test', 'results.json'));
  cssFilename = 'iconr.css';
  iconrHeader = '/* generated by iconr */\n\n';
  results = [];
  if (opts.verbose) {
    log = {
      appStart: microtime.now(),
      appEnd: 0,
      svgCount: 0,
      svgSize: 0
    };
  }
  return pathExists(inDir, function(exists) {
    if (exists) {
      return readDir(inDir).then(function(files) {
        return util.filterNonSvgFiles(files);
      }).then(function(filteredFiles) {
        var queue;
        if (opts.verbose) {
          log.svgCount = filteredFiles.length;
        }
        queue = [];
        filteredFiles.forEach(function(file) {
          var svgPath;
          svgPath = path.resolve(inDir, file);
          queue.push(readFile(svgPath, 'utf8'));
          if (opts.verbose) {
            log.svgSize += fs.statSync(svgPath).size;
          }
          return results.push({
            name: util.trimExt(file),
            svgpath: svgPath
          });
        });
        return Q.all(queue);
      }).then(function() {
        return iconrHeader + util.createCssRules(resultsTemp);
      }).then(function(cssString) {
        if (opts.pretty) {
          cssString = util.prettyCss(cssString);
        }
        return writeFile(path.resolve(outDir, '..', cssFilename), cssString);
      }).fail(function(error) {
        return msg.data('error', error);
      })["finally"](function() {
        if (opts.debug) {
          msg.dump(resultsTemp);
        }
        if (opts.verbose) {
          log.appEnd = microtime.now();
          return msg.summary(log);
        }
      }).done();
    } else {
      return msg.log('error', 'wrongDirectory');
    }
  });
};
