// Generated by CoffeeScript 1.6.3
var Q, fs, log, path, pathExists, readDir, readFile, svg2png, ut, util, _;

fs = require('fs');

path = require('path');

_ = require('underscore');

Q = require('q');

svg2png = require('svg2png');

util = require(path.resolve(__dirname, './', 'util'));

log = require(path.resolve(__dirname, './', 'log'));

ut = require('util');

Q.longStackSupport = true;

readDir = Q.denodeify(fs.readdir);

readFile = Q.denodeify(fs.readFile);

pathExists = Q.denodeify(fs.exists);

module.exports = function(args) {
  var inDir, outDir, results;
  inDir = path.resolve(__dirname, '..', 'test', 'inDir');
  outDir = path.resolve(__dirname, '..', 'test', 'outDir');
  results = [];
  return pathExists(inDir, function(exists) {
    if (exists) {
      return readDir(inDir).then(function(files) {
        return util.filterNonSvgFiles(files);
      }).then(function(filteredFiles) {
        var queue;
        queue = [];
        filteredFiles.forEach(function(file) {
          var filepath;
          filepath = path.resolve(inDir, file);
          queue.push(readFile(filepath, 'utf8'));
          return results.push({
            name: util.trimExt(file),
            filepath: filepath
          });
        });
        return Q.all(queue);
      }).then(function(svgData) {
        var queue;
        queue = [];
        svgData.forEach(function(svg) {
          return queue.push(util.optimizeSvg(svg));
        });
        return Q.all(queue);
      }).then(function(data) {
        return _.each(data, function(obj, i) {
          var svgData;
          svgData = {
            svgsrc: obj.data,
            svgdatauri: util.encodeImage(obj.data, 'base64', 'svg'),
            height: util.roundNum(obj.info.height),
            width: util.roundNum(obj.info.width)
          };
          return _.extend(results[i], svgData);
        });
      }).then(function() {
        return console.log(JSON.stringify(results, null, ' '));
      }).fail(function(error) {
        return log.data('error', error);
      }).done();
    } else {
      return log.msg('error', 'wrongDirectory');
    }
  });
};
