// Generated by CoffeeScript 1.6.3
var displayHelp, displayVersion, fs, iconr, path;

path = require('path');

fs = require('fs');

iconr = require(path.join(__dirname, '..', 'lib', 'app'));

displayVersion = function() {
  var pkg;
  pkg = require(path.join(__dirname, '..', 'package.json'));
  return console.log(pkg.version);
};

displayHelp = function() {
  var doc, filepath;
  filepath = path.join(__dirname, '..', 'lang', 'help.txt');
  doc = fs.readFileSync(filepath, 'utf8');
  return console.log('\n' + doc + '\n');
};

module.exports = function(argv) {
  var flags;
  flags = {
    verbose: argv.verbose || argv.v ? true : false,
    analytics: argv.analytics || argv.a ? true : false,
    pretty: argv.pretty || argv.p ? true : false,
    base64: argv.base64 || argv.b ? true : false,
    nopng: argv.nopng || argv.n ? true : false,
    stdout: argv.stdout || argv.s ? true : false,
    optimizesvg: argv.optimizesvg || argv.o ? true : false,
    killcomment: argv.killcomment || argv.k ? true : false,
    debug: argv.debug || argv.d ? true : false,
    filename: argv.filename || argv.f ? argv.filename || argv.f : null,
    classname: argv.classname || argv.c ? argv.classname || argv.c : ''
  };
  if (argv._.length > 0) {
    return iconr(argv._, flags);
  }
  if (argv.version || argv.V) {
    return displayVersion();
  }
  if (argv.help || argv.h) {
    return displayHelp();
  }
  if (!argv._.length) {
    return displayHelp();
  }
};
