// Generated by CoffeeScript 1.6.3
var displayHelp, displayVersion, fs, iconr, path;

path = require('path');

fs = require('fs');

iconr = require(path.join(__dirname, '..', 'lib', 'app'));

displayVersion = function() {
  var pkg;
  pkg = require(path.join(__dirname, '..', 'package.json'));
  return console.log(pkg.version);
};

displayHelp = function() {
  var doc, filepath;
  filepath = path.join(__dirname, '..', 'lang', 'help.txt');
  doc = fs.readFileSync(filepath, 'utf8');
  return console.log('\n' + doc + '\n');
};

module.exports = function(argv) {
  var flags;
  flags = {
    verbose: argv.verbose || argv.v ? true : false,
    pretty: argv.pretty || argv.p ? true : false,
    debug: argv.debug || argv.d ? true : false
  };
  if (argv._.length > 0) {
    return iconr(argv._, flags);
  }
  if (argv.version || argv.V) {
    return displayVersion();
  }
  if (argv.help || argv.h) {
    return displayHelp();
  }
  if (!argv._.length) {
    return displayHelp();
  }
};
