// Generated by CoffeeScript 1.6.3
var colorMap, colors, messages, path;

path = require('path');

colors = require('colors');

messages = require(path.resolve(__dirname, '..', 'lang', 'messages.json'));

colorMap = {
  error: 'red',
  warn: 'yellow',
  info: 'blue',
  ask: 'green',
  list: 'white'
};

exports.str = function(type, key, data) {
  return messages[type][key];
};

exports.msg = function(type, key, data) {
  if (typeof data === 'undefined') {
    data = '';
  }
  return console.log(messages[type][key][colorMap[type]], data);
};

exports.data = function(type, msg, data) {
  if (typeof data === 'undefined') {
    data = '';
  }
  if (type === 'error') {
    return console.error(msg[colorMap[type]], data);
  } else {
    return console.error(msg[colorMap[type]], data);
  }
};
