// Generated by CoffeeScript 1.6.3
var colorMap, colors, messages, path;

path = require('path');

colors = require('colors');

messages = require(path.resolve(__dirname, '..', 'lang', 'messages.json'));

colorMap = {
  error: 'red',
  warn: 'yellow',
  info: 'blue',
  ask: 'green',
  list: 'white'
};

module.exports = {
  str: function(type, key, data) {
    return messages[type][key];
  },
  log: function(type, key, data) {
    if (typeof data === 'undefined') {
      data = '';
    }
    return console.log(messages[type][key][colorMap[type]], data);
  },
  data: function(type, msg, data) {
    if (typeof data === 'undefined') {
      data = '';
    }
    if (type === 'error') {
      return console.error(msg[colorMap[type]], data);
    } else {
      return console.log(msg[colorMap[type]], data);
    }
  },
  summary: function(log) {
    var totalTime;
    totalTime = (log.appEnd - log.appStart) / 1000000;
    console.log('\n');
    console.log(' ' + ' SUMMARY: '.yellow.inverse);
    console.log(' - converted '.yellow + log.svgCount + ' SVG images totaling '.yellow + log.svgSize + ' bytes'.yellow);
    console.log(' - it took '.yellow + totalTime + ' seconds'.yellow);
    console.log(' - an average of '.yellow + (totalTime / log.svgCount) + ' seconds per icon'.yellow);
    return console.log('\n');
  },
  dump: function(json) {
    return console.log(JSON.stringify(json, null, ' '));
  }
};
