// Generated by CoffeeScript 1.7.1
var colorMap, colors, messages, path;

path = require('path');

colors = require('colors');

messages = require(path.resolve(__dirname, '..', 'lang', 'messages.json'));

colorMap = {
  error: 'red',
  warn: 'yellow',
  info: 'blue',
  ask: 'green',
  list: 'white'
};

module.exports = {
  str: function (type, key, data) {
    return messages[type][key];
  },
  log: function (type, key, data) {
    if (typeof data === 'undefined') {
      data = '';
    }
    return console.log(messages[type][key][colorMap[type]], data);
  },
  data: function (type, msg, data) {
    if (typeof data === 'undefined') {
      data = '';
    }
    if (type === 'error') {
      return console.error(msg[colorMap[type]], data);
    } else {
      return console.log(msg[colorMap[type]], data);
    }
  },
  analytics: function(log) {
    var totalTime;
    totalTime = (log.appEnd - log.appStart) / 1000000;
    console.log('\n');
    console.log(' ' + ' SUMMARY: '.magenta.inverse);
    console.log(' ☉ converted '.magenta + log.svgCount + ' SVG images totaling '.magenta + log.svgSize + ' bytes'.magenta);
    console.log(' ☉ into a CSS file that is '.magenta + log.cssSize + ' bytes'.magenta);
    console.log(' ☉ it took '.magenta + totalTime + ' seconds'.magenta);
    console.log(' ☉ an average of '.magenta + (totalTime / log.svgCount) + ' seconds per icon'.magenta);
    return console.log('\n');
  },
  dump: function(json) {
    return console.log(JSON.stringify(json, null, ' '));
  }
};
