// Generated by CoffeeScript 1.6.3
"use strict";
var convert, webpage;

webpage = require('webpage');

convert = function(source, destination, height, width) {
  var page;
  page = webpage.create();
  return page.open(source, function(status) {
    if (status !== 'success') {
      console.error('Couldn\'t load the source SVG!');
      phantom.exit();
      return;
    }
    page.zoomFactor = 1;
    page.viewportSize = {
      width: Math.round(width),
      height: Math.round(height)
    };
    return setTimeout((function() {
      page.render(destination);
      return phantom.exit();
    }), 0);
  });
};

if (phantom.args.length !== 4) {
  console.error('Missing arguments! Usage: source SVG, destination PNG, height & width');
  phantom.exit();
} else {
  convert(phantom.args[0], phantom.args[1], phantom.args[2], phantom.args[3]);
}
