var Q, execFile, fs, mime, path, phantomjs, pretty, svgToPngFile, svgo, writeFile, _;

fs = require('fs');

path = require('path');

execFile = require('child_process').execFile;

mime = require('mime');

_ = require('lodash');

Q = require('q');

svgo = new (require('svgo'))();

pretty = require('cssbeautify');

phantomjs = path.resolve(__dirname, '../node_modules/phantomjs/bin/phantomjs');

svgToPngFile = path.resolve(__dirname, './', 'svgToPng.js');

writeFile = Q.denodeify(fs.writeFile);

module.exports = {
  trimFilename: function(filename) {
    var index;
    index = filename.lastIndexOf('.css');
    if (index !== -1) {
      filename = filename.substring(0, index);
    }
    return filename;
  },
  encodeImage: function(data, type, format) {
    var encoded, formatMap, str;
    str = ',';
    formatMap = {
      'svg': '\'data:image/svg+xml',
      'png': '\'data:image/png'
    };
    if (type === 'base64') {
      str = ';base64,';
      encoded = new Buffer(data).toString('base64');
    } else {
      encoded = encodeURIComponent(new Buffer(data).toString());
    }
    return formatMap[format] + str + encoded + '\'';
  },
  roundNum: function(num) {
    return Math.round(num).toString();
  },
  hasSpace: function(filename) {
    return filename.indexOf(' ') >= 0;
  },
  replaceSpaceInFilename: function(oldFilename, newFilename, inDir) {
    return fs.renameSync(inDir + '/' + oldFilename, inDir + '/' + newFilename);
  },
  trimExt: function(filename) {
    return filename.replace(/\.[^/.]+$/, '');
  },
  filterNonSvgFiles: function(files, dir) {
    return _.filter(files, function(file) {
      return fs.statSync(path.join(dir + '/' + file)).isFile() === true && mime.lookup(file) === 'image/svg+xml';
    });
  },
  optimizeSvg: function(data) {
    var d;
    d = Q.defer();
    svgo.optimize(data, function(result) {
      if (result.error) {
        d.reject(new Error(result.error));
      }
      result.original = data;
      return d.resolve(result);
    });
    return d.promise;
  },
  saveSvgAsPng: function(sourceFileName, destinationFileName, height, width) {
    var args, d;
    args = [phantomjs, svgToPngFile, sourceFileName, destinationFileName, height, width];
    d = Q.defer();
    execFile(process.execPath, args, function(err, stdout, stderr) {
      if (err) {
        return d.reject(new Error(err));
      } else if (stdout.length > 0) {
        return d.reject(new Error(stdout.toString().trim()));
      } else {
        return d.resolve(destinationFileName);
      }
    });
    return d.promise;
  },
  createCssRules: function(results, opts) {
    var css, cssClassnamePrefix, cssNoDataUri, cssNoInlineSvg, cssSvg;
    cssClassnamePrefix = opts.classname != null ? opts.classname : '';
    css = [];
    cssSvg = '';
    cssNoInlineSvg = '';
    cssNoDataUri = '';
    if (!opts.killcomment) {
      cssSvg += '/* generated by iconr */\n\n';
    }
    _.each(results, function(res, i) {
      var height, width;
      height = !isNaN(res.height) ? "height:" + res.height + "px;" : '';
      width = !isNaN(res.width) ? "width:" + res.width + "px;" : '';
      cssSvg += ("." + (cssClassnamePrefix + res.name) + "{") + ("" + height) + ("" + width) + ("background-image:url(" + res.svgdatauri + ");") + "}";
      if (!opts.nopngdata) {
        cssNoInlineSvg += (".no-inlinesvg ." + (cssClassnamePrefix + res.name) + "{") + ("background-image:url(" + res.pngdatauri + ");") + "}";
      }
      if (!opts.nopng && !opts.stdout) {
        return cssNoDataUri += (".no-datauri ." + (cssClassnamePrefix + res.name) + "{") + ("background-image:url('" + res.pngpath + "');") + "}";
      }
    });
    css.push(cssSvg, cssNoInlineSvg, cssNoDataUri);
    return css;
  },
  prettyCss: function(css) {
    return pretty(css);
  },
  mungeCss: function(cssArray) {
    var css;
    css = cssArray.join('');
    return css;
  },
  saveCss: function(filename, cssArr, opts) {
    var css;
    if (opts.separatecss) {
      if (opts.pretty) {
        cssArr = cssArr.map((function(_this) {
          return function(css) {
            return _this.prettyCss(css);
          };
        })(this));
      }
      writeFile(filename + '.css', cssArr[0]);
      if (cssArr[1].length !== 0) {
        writeFile(filename + '-noinlinesvg.css', cssArr[1]);
      }
      if (cssArr[2].length !== 0) {
        return writeFile(filename + '-nodatauri.css', cssArr[2]);
      }
    } else {
      css = this.mungeCss(cssArr);
      if (opts.pretty) {
        css = this.prettyCss(css);
      }
      return writeFile(filename + '.css', css);
    }
  }
};
